var tableauQuestion = [
    {   question : "¿Cual es la edad recomendada para realizar el curso TCP?",
        propositionA : "18 años",
        propositionB : "25 años",
        propositionC : "No hay edad recomendada",
        propositionD : "35 años",
        reponse : "D"},

    {   question : "¿Se necesita permiso de residencia/trabajo para poder trabajar en una aerolínea?",
        propositionA : "Si",
        propositionB : "No",
        propositionC : "Depende del país",
        propositionD : "Solo de residencia",
        reponse : "C"},

    {   question : "¿Se necesita pasaporte para poder trabajar como auxiliar de vuelo?",
        propositionA : "Si",
        propositionB : "No",
        propositionC : "Depende del país",
        propositionD : "Depende de tu nacionalidad",
        reponse : "A"},

  {   question : "¿Cuál es la altura mínima para las chicas (sin tacones)?",
        propositionA : "1,58m",
        propositionB : "Dependiendo de la aerolinea",
        propositionC : "1,48m",
        propositionD : "No hay altura especificada",
        reponse : "A"},

  {   question : "¿Qué nivel de alcohol en sangre se clasifican como permitido mientras estas intoxicado?",
        propositionA : "0.05%",
        propositionB : "0.18%",
        propositionC : "0.08%",
        propositionD : "0.06%",
        reponse : "C"},

  {   question : "¿Cuál es la altura mínima para los chicos?",
        propositionA : "1,68m",
        propositionB : "2,12m",
        propositionC : "No hay altura especificada",
        propositionD : "Dependiendo de la aerolinea",
        reponse : "A"},

  {   question : "¿Hay que saber nadar para poder manejar un avion o helicoptero?",
        propositionA : "No",
        propositionB : "Depende del puesto al que postules",
        propositionC : "Si",
        propositionD : "Depende de la aerolinea",
        reponse : "C"},

  {   question : "¿Quien es el mejor administrador de la ciudad? <3 I love you",
        propositionA : "Bebeleche",
        propositionB : "Calvo",
        propositionC : "Kairasi",
        propositionD : "Dalton",
        reponse : "D"},

  {   question : "¿Se puede trabajar en una aerolínea si tienes tatuajes o piercings?",
        propositionA : "Si",
        propositionB : "Depende de la aerolinea",
        propositionC : "No",
        propositionD : "Depende si son visibles o no",
        reponse : "B"},

  {   question : "¿Es necesario tener carnet de conducir para pilotar?",
        propositionA : "Si, es indispensable",
        propositionB : "No",
        propositionC : "Depende del puesto al que examinas",
        propositionD : "No lo se",
        reponse : "B"},
]
