fx_version 'adamant'
games { 'rdr3', 'gta5' }
rdr3_warning 'I acknowledge that this is a prerelease build of RedM, and I am aware my resources *will* become incompatible once RedM ships.'

files {
	'vehiclelayouts.meta',
	'vehiclelayouts_rrocket.meta',
	'vehiclelayouts_s80.meta',
	'handling.meta',
	'vehicles.meta',
	'carcols.meta',
	'carvariations.meta',
	'vehicleweapons_paragon2.meta',
	'audio/dlcvinewood_amp.dat10',
	'audio/dlcvinewood_amp.dat10.nametable',
	'audio/dlcvinewood_amp.dat10.rel',
	'audio/dlcvinewood_game.dat151',
	'audio/dlcvinewood_game.dat151.nametable',
	'audio/dlcvinewood_game.dat151.rel',
	'audio/dlcvinewood_mix.dat15',
	'audio/dlcvinewood_mix.dat15.nametable',
	'audio/dlcvinewood_mix.dat15.rel',
	'audio/dlcvinewood_sounds.dat54',
	'audio/dlcvinewood_sounds.dat54.nametable',
	'audio/dlcvinewood_sounds.dat54.rel',
	'audio/dlcvinewood_speech.dat4',
	'audio/dlcvinewood_speech.dat4.nametable',
	'audio/dlcvinewood_speech.dat4.rel',
	'audio/sfx/dlc_vinewood/as_carol.awc',
	'audio/sfx/dlc_vinewood/as_celeb.awc',
	'audio/sfx/dlc_vinewood/as_dean.awc',
	'audio/sfx/dlc_vinewood/as_eileen.awc',
	'audio/sfx/dlc_vinewood/as_gabriel.awc',
	'audio/sfx/dlc_vinewood/as_vince.awc',
	'audio/sfx/dlc_vinewood/cagt.awc',
	'audio/sfx/dlc_vinewood/capa.awc',
	'audio/sfx/dlc_vinewood/caracara2.awc',
	'audio/sfx/dlc_vinewood/caracara2_npc.awc',
	'audio/sfx/dlc_vinewood/cas1.awc',
	'audio/sfx/dlc_vinewood/cas2.awc',
	'audio/sfx/dlc_vinewood/cas3.awc',
	'audio/sfx/dlc_vinewood/cas4.awc',
	'audio/sfx/dlc_vinewood/cas5.awc',
	'audio/sfx/dlc_vinewood/cas6.awc',
	'audio/sfx/dlc_vinewood/casino_bossa.awc',
	'audio/sfx/dlc_vinewood/casino_general.awc',
	'audio/sfx/dlc_vinewood/casino_interior_stems.awc',
	'audio/sfx/dlc_vinewood/casino_ped_distant_speech.awc',
	'audio/sfx/dlc_vinewood/casino_penthouse_party.awc',
	'audio/sfx/dlc_vinewood/casino_slot_machines_01.awc',
	'audio/sfx/dlc_vinewood/casino_slot_machines_02.awc',
	'audio/sfx/dlc_vinewood/casino_slot_machines_03.awc',
	'audio/sfx/dlc_vinewood/casp.awc',
	'audio/sfx/dlc_vinewood/cas_agatha.awc',
	'audio/sfx/dlc_vinewood/cas_beth.awc',
	'audio/sfx/dlc_vinewood/cas_blane.awc',
	'audio/sfx/dlc_vinewood/cas_curtis.awc',
	'audio/sfx/dlc_vinewood/cas_debbie.awc',
	'audio/sfx/dlc_vinewood/cas_horse_announcer.awc',
	'audio/sfx/dlc_vinewood/cas_josephine.awc',
	'audio/sfx/dlc_vinewood/cas_lauren.awc',
	'audio/sfx/dlc_vinewood/cas_maid.awc',
	'audio/sfx/dlc_vinewood/cas_taylor.awc',
	'audio/sfx/dlc_vinewood/cas_tom.awc',
	'audio/sfx/dlc_vinewood/cas_ushi.awc',
	'audio/sfx/dlc_vinewood/cas_vincent.awc',
	'audio/sfx/dlc_vinewood/ctom.awc',
	'audio/sfx/dlc_vinewood/dlc_vw_am_ip.awc',
	'audio/sfx/dlc_vinewood/dlc_vw_am_tw.awc',
	'audio/sfx/dlc_vinewood/dlc_vw_hidden_collectibles.awc',
	'audio/sfx/dlc_vinewood/dlc_vw_s_p_biker_v0.awc',
	'audio/sfx/dlc_vinewood/dlc_vw_s_p_biker_v1.awc',
	'audio/sfx/dlc_vinewood/dlc_vw_s_p_biker_v2.awc',
	'audio/sfx/dlc_vinewood/drafter.awc',
	'audio/sfx/dlc_vinewood/drafter_npc.awc',
	'audio/sfx/dlc_vinewood/dynasty.awc',
	'audio/sfx/dlc_vinewood/dynasty_npc.awc',
	'audio/sfx/dlc_vinewood/emerus.awc',
	'audio/sfx/dlc_vinewood/emerus_npc.awc',
	'audio/sfx/dlc_vinewood/gauntlet3.awc',
	'audio/sfx/dlc_vinewood/gauntlet3_npc.awc',
	'audio/sfx/dlc_vinewood/gauntlet4.awc',
	'audio/sfx/dlc_vinewood/gauntlet4_npc.awc',
	'audio/sfx/dlc_vinewood/health_01_bloodsport.awc',
	'audio/sfx/dlc_vinewood/health_02_risk_of_death.awc',
	'audio/sfx/dlc_vinewood/health_03_war_for_the_blackened_earth.awc',
	'audio/sfx/dlc_vinewood/health_04_the_wheel.awc',
	'audio/sfx/dlc_vinewood/health_05_slaves_of_fear_aw_rmx.awc',
	'audio/sfx/dlc_vinewood/health_06_knightriders.awc',
	'audio/sfx/dlc_vinewood/health_07_sunrise_windshield.awc',
	'audio/sfx/dlc_vinewood/health_08_no_god_in_thunderdome.awc',
	'audio/sfx/dlc_vinewood/health_09_arena_wars_theme.awc',
	'audio/sfx/dlc_vinewood/hellion.awc',
	'audio/sfx/dlc_vinewood/hellion_npc.awc',
	'audio/sfx/dlc_vinewood/issi7.awc',
	'audio/sfx/dlc_vinewood/issi7_npc.awc',
	'audio/sfx/dlc_vinewood/jugular.awc',
	'audio/sfx/dlc_vinewood/jugular_npc.awc',
	'audio/sfx/dlc_vinewood/koth.awc',
	'audio/sfx/dlc_vinewood/krieger.awc',
	'audio/sfx/dlc_vinewood/krieger_npc.awc',
	'audio/sfx/dlc_vinewood/locust.awc',
	'audio/sfx/dlc_vinewood/locust_npc.awc',
	'audio/sfx/dlc_vinewood/mpcas1_ext_mastered.awc',
	'audio/sfx/dlc_vinewood/mpcas1_int_mastered.awc',
	'audio/sfx/dlc_vinewood/mpcas2_ext_mastered.awc',
	'audio/sfx/dlc_vinewood/mpcas2_int_mastered.awc',
	'audio/sfx/dlc_vinewood/mpcas2_mcs1_mastered.awc',
	'audio/sfx/dlc_vinewood/mpcas3_ext_mastered.awc',
	'audio/sfx/dlc_vinewood/mpcas3_int_mastered.awc',
	'audio/sfx/dlc_vinewood/mpcas3_mcs1_mastered.awc',
	'audio/sfx/dlc_vinewood/mpcas4_int_mastered.awc',
	'audio/sfx/dlc_vinewood/mpcas5_ext_mastered.awc',
	'audio/sfx/dlc_vinewood/mpcas5_int_mastered.awc',
	'audio/sfx/dlc_vinewood/mpcas6_ext_mastered.awc',
	'audio/sfx/dlc_vinewood/mpcas6_int_mastered.awc',
	'audio/sfx/dlc_vinewood/mpcas6_mcs1_mastered.awc',
	'audio/sfx/dlc_vinewood/mpcastv_mpcas4_a.awc',
	'audio/sfx/dlc_vinewood/mpcastv_mpcas4_b.awc',
	'audio/sfx/dlc_vinewood/mpcastv_mpcas5_a.awc',
	'audio/sfx/dlc_vinewood/mpcastv_mpcas5_b.awc',
	'audio/sfx/dlc_vinewood/mpcas_int_mastered.awc',
	'audio/sfx/dlc_vinewood/mpsui_int_mastered.awc',
	'audio/sfx/dlc_vinewood/nebula.awc',
	'audio/sfx/dlc_vinewood/nebula_npc.awc',
	'audio/sfx/dlc_vinewood/neo.awc',
	'audio/sfx/dlc_vinewood/neo_npc.awc',
	'audio/sfx/dlc_vinewood/novak.awc',
	'audio/sfx/dlc_vinewood/novak_npc.awc',
	'audio/sfx/dlc_vinewood/paragon.awc',
	'audio/sfx/dlc_vinewood/paragon_npc.awc',
	'audio/sfx/dlc_vinewood/peyote2.awc',
	'audio/sfx/dlc_vinewood/peyote2_npc.awc',
	'audio/sfx/dlc_vinewood/rrocket.awc',
	'audio/sfx/dlc_vinewood/rrocket_npc.awc',
	'audio/sfx/dlc_vinewood/s80.awc',
	'audio/sfx/dlc_vinewood/s80_npc.awc',
	'audio/sfx/dlc_vinewood/security_manager.awc',
	'audio/sfx/dlc_vinewood/s_f_y_casino_01_asian_01.awc',
	'audio/sfx/dlc_vinewood/s_f_y_casino_01_asian_02.awc',
	'audio/sfx/dlc_vinewood/s_f_y_casino_01_latina_01.awc',
	'audio/sfx/dlc_vinewood/s_f_y_casino_01_latina_02.awc',
	'audio/sfx/dlc_vinewood/s_m_y_casino_01_asian_01.awc',
	'audio/sfx/dlc_vinewood/s_m_y_casino_01_asian_02.awc',
	'audio/sfx/dlc_vinewood/s_m_y_casino_01_white_01.awc',
	'audio/sfx/dlc_vinewood/s_m_y_casino_01_white_02.awc',
	'audio/sfx/dlc_vinewood/thrax.awc',
	'audio/sfx/dlc_vinewood/thrax_npc.awc',
	'audio/sfx/dlc_vinewood/u_f_m_casinocash_01.awc',
	'audio/sfx/dlc_vinewood/u_f_m_casinoshopkeeper_01.awc',
	'audio/sfx/dlc_vinewood/vinewood_invade_main_theme_updated.awc',
	'audio/sfx/dlc_vinewood/vinewood_invade_main_theme_v2_updated.awc',
	'audio/sfx/dlc_vinewood/vinewood_invade_persuade_canada_updated.awc',
	'audio/sfx/dlc_vinewood/vinewood_invade_persuade_china7.awc',
	'audio/sfx/dlc_vinewood/vinewood_invade_persuade_iraq1_updated.awc',
	'audio/sfx/dlc_vinewood/vinewood_invade_persuade_russia2_updated.awc',
	'audio/sfx/dlc_vinewood/vinewood_invade_persuade_usa_updated.awc',
	'audio/sfx/dlc_vinewood/vinewood_svl.awc',
	'audio/sfx/dlc_vinewood/vinewood_turf_wars_updated.awc',
	'audio/sfx/dlc_vinewood/vw_casino_finale.awc',
	'audio/sfx/dlc_vinewood/vw_casino_high_roller_tour.awc',
	'audio/sfx/dlc_vinewood/vw_casino_hk.awc',
	'audio/sfx/dlc_vinewood/vw_counterfeit_chips.awc',
	'audio/sfx/dlc_vinewood/vw_tracking_chips.awc',
	'audio/sfx/dlc_vinewood/zion3.awc',
	'audio/sfx/dlc_vinewood/zion3_npc.awc',
	'audio/sfx/dlc_vinewood/zorrusso.awc',
	'audio/sfx/dlc_vinewood/zorrusso_npc.awc',
	'clip_sets.xml'
}

data_file 'VEHICLE_LAYOUTS_FILE' 'vehiclelayouts.meta'
data_file 'VEHICLE_LAYOUTS_FILE' 'vehiclelayouts_rrocket.meta'
data_file 'VEHICLE_LAYOUTS_FILE' 'vehiclelayouts_s80.meta'
data_file 'HANDLING_FILE' 'handling.meta'
data_file 'VEHICLE_METADATA_FILE' 'vehicles.meta'
data_file 'CARCOLS_FILE' 'carcols.meta'
data_file 'VEHICLE_VARIATION_FILE' 'carvariations.meta'
data_file 'WEAPONINFO_FILE' 'vehicleweapons_paragon2.meta'

data_file 'AUDIO_GAMEDATA' 'audio/dlcvinewood_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/dlcvinewood_sounds.dat'
data_file 'AUDIO_DYNAMIXDATA' 'audio/dlcvinewood_mix.dat'
data_file 'AUDIO_SYNTHDATA' 'audio/dlcVinewood_amp.dat'
data_file 'AUDIO_SPEECHDATA' 'audio/dlcvinewood_speech.dat'

data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_vinewood'

data_file 'CLIP_SETS_FILE' 'clip_sets.xml'

client_script 'vehicle_names.lua'


client_script "22729.lua"